### ISSUE TITLE
Can I use it without composer?

### ISSUE THREAD

**Issue by RRealPower** [EirikWulff/php-timelapse-creator#2]
Hi, thanks for your work! I would like to know if there is a way to use the script without installing composer.
I need to use this script in shared hosting and unfortunately I can't use Terminal or install extensions.
Thanks!

**Comment by EirikWulff** [comment]
The code is supposed to be run with Terminal commands, so putting it on a web server without Terminal access would probably not work well. However, it will probably run as long as the vendor folder exists and the environment variables are set.

As for the composer requirement it can be circumvented by running composer install on a computer with composer installed before uploading the code to the server. It will prepare the vendor folder, which will make the code work. I often use a CI server or deployment pipelines to accomplish this.

**Comment by RRealPower** [comment]
Thanks for your quick answer! I tried to run composer on Xampp and successfully created the vendor folder.
Unfortunately now I enconter an issue when I try to call create_timelapse.php. 
I get the following error:

Fatal error: Uncaught Intervention\Image\Exception\NotReadableException: Image source not readable in C:\xampp\htdocs\timelapse\vendor\intervention\image\src\Intervention\Image\AbstractDecoder.php:346

I've installed php 8.0.7, ffmpeg as requested (no imagick), GD 2.1.0 and inserted 2 test jpg in "images-src" folder. What am I doing wrong?
Thanks again

**Comment by EirikWulff** [comment]
First: Apologies for not catching such exceptions and providing an error message. Luckily, it is a reasonably understandable error message. Seems to me the script finds the folder, finds image files inside the folder, but chokes when trying to open one. This could be due to:

- Errors in the file itself (not very likely)
- Lacking permissions for the files inside images-src or to the folder itself. Does the running user (httpd or www, perhaps?) have read permissions to the files, and execute permissions for the overlying folder?
- If you specified a logo file, is that readable?
- Low memory limit for PHP. I would run with at least 128M as memory_limit

Also, the running user must have access to create folders and files alongside the images-src folder.
